import {PRESETS,TEMPLATES,BACKGROUND_STYLES,preset,template,splitLineup,compactDetails,safeFilename,fontSizeForText} from './poster-core.js';
import {createBackgroundRenderers} from './background-art.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$('#poster'),ctx=canvas.getContext('2d');
const stock={
  stock1:'https://images.pexels.com/photos/8448565/pexels-photo-8448565.jpeg?auto=compress&cs=tinysrgb&w=1800',
  stock2:'https://images.pexels.com/photos/5192299/pexels-photo-5192299.jpeg?auto=compress&cs=tinysrgb&w=1800',
  stock3:'https://images.pexels.com/photos/10024815/pexels-photo-10024815.jpeg?auto=compress&cs=tinysrgb&w=1800',
  stockTurntable:'https://images.pexels.com/photos/3550240/pexels-photo-3550240.jpeg?auto=compress&cs=tinysrgb&w=1800',
  stockSynth:'https://images.pexels.com/photos/28539681/pexels-photo-28539681.jpeg?auto=compress&cs=tinysrgb&w=1800',
  stockUrban:'https://images.pexels.com/photos/19455312/pexels-photo-19455312.jpeg?auto=compress&cs=tinysrgb&w=1800'
};
const palettes=[['#07070b','#ff2fb2','#6ef2ff','#ffffff'],['#07090c','#f04d32','#ffcc48','#f5f1e8'],['#0a0a0a','#d7d7d7','#ffffff','#7c8794'],['#080b22','#6d5cff','#35e6ff','#f5f7ff'],['#151006','#ffbd66','#ff6f61','#fff2d7'],['#0b0a10','#b89958','#ece0bd','#ffffff'],['#090b11','#386ca6','#99b8d7','#f2f6fa'],['#100b08','#e57231','#d8b36a','#f5ead8']];
const state={title:'',tagline:'',date:'',time:'',venue:'',city:'',lineup:'',price:'',age:'',organizer:'',extra:'',url:'',template:'neon',palette:0,bg:'procedural',bgStyle:'waves',clipart:'none',variation:0,titleFont:'Impact',bodyFont:'Arial',overlay:.35,grain:.25,density:'normal',image:null,imageX:.5,imageY:.5,imageScale:1,stockImages:{}};
const extraBackgrounds=createBackgroundRenderers(ctx,canvas,state);
function init(){
 $('#templates').innerHTML=TEMPLATES.map(t=>`<button class="template ${t.id===state.template?'active':''}" data-template="${t.id}"><strong>${t.name}</strong><span>${t.tags.join(' · ')}</span></button>`).join('');
 $('#palettes').innerHTML=palettes.map((p,i)=>`<button class="swatch ${i===state.palette?'active':''}" data-palette="${i}" style="background:linear-gradient(135deg,${p[1]} 0 50%,${p[2]} 50%)" aria-label="Palette ${i+1}"></button>`).join('');
 $('#backgroundStyle').innerHTML=BACKGROUND_STYLES.map(bg=>`<option value="${bg.id}">${bg.label}</option>`).join('');$('#backgroundStyle').value=state.bgStyle;
 $('#preset').innerHTML=Object.entries(PRESETS).map(([k,p])=>`<option value="${k}">${p.label}</option>`).join('');$('#preset').value='instagram';
 $$('[data-field]').forEach(el=>el.addEventListener('input',()=>{state[el.dataset.field]=el.value;render()}));
 $('#templates').onclick=e=>{const b=e.target.closest('[data-template]');if(!b)return;state.template=b.dataset.template;const t=template(state.template);state.titleFont=t.titleFont;state.bodyFont=t.bodyFont;$('#titleFont').value=state.titleFont;$('#bodyFont').value=state.bodyFont;$('.template.active')?.classList.remove('active');b.classList.add('active');$('#templateName').textContent=t.name;if(t.id==='hiphop'&&state.bg==='procedural')state.bgStyle='urban';if(t.id==='turntablist'&&state.bg==='procedural')state.bgStyle='turntable';if(t.id==='synthwave'&&state.bg==='procedural')state.bgStyle='synth';if(t.id==='hardcore'&&state.bg==='procedural')state.bgStyle='xerox';$('#backgroundStyle').value=state.bgStyle;render()};
 $('#palettes').onclick=e=>{const b=e.target.closest('[data-palette]');if(!b)return;state.palette=Number(b.dataset.palette);$('.swatch.active')?.classList.remove('active');b.classList.add('active');render()};
 $$('.bg').forEach(b=>b.onclick=()=>{state.bg=b.dataset.bg;$$('.bg').forEach(x=>x.classList.toggle('active',x===b));if(stock[state.bg])loadStock(state.bg);render()});
 $('#backgroundStyle').onchange=e=>{state.bgStyle=e.target.value;state.bg='procedural';$$('.bg').forEach(x=>x.classList.toggle('active',x.dataset.bg==='procedural'));render()};
 $('#clipart').onchange=e=>{state.clipart=e.target.value;render()};
 $('#imageUpload').onchange=e=>loadUserImage(e.target.files[0]);$('#removeImage').onclick=()=>{state.image=null;state.bg=state.bg==='image'?'procedural':state.bg;render()};$('#centerImage').onclick=()=>{state.imageX=.5;state.imageY=.5;render()};
 $('#modeToggle').onclick=()=>{const a=$('#advanced');a.hidden=!a.hidden;$('#modeToggle').textContent=a.hidden?'Advanced':'Basic'};
 $('#titleFont').onchange=e=>{state.titleFont=e.target.value;render()};$('#bodyFont').onchange=e=>{state.bodyFont=e.target.value;render()};$('#imageScale').oninput=e=>{state.imageScale=Number(e.target.value);render()};$('#overlay').oninput=e=>{state.overlay=Number(e.target.value);render()};$('#grain').oninput=e=>{state.grain=Number(e.target.value);render()};$('#density').onchange=e=>{state.density=e.target.value;render()};
 $('#preset').onchange=resizeToPreset;$('#generate').onclick=()=>{state.variation=(state.variation+1)%31;render()};$('#regenerate').onclick=()=>{state.variation=(state.variation+3)%47;render()};$('#randomColor').onclick=()=>{state.palette=(state.palette+1)%palettes.length;initPaletteOnly();render()};
 $('#download').onclick=download;$('#downloadTop').onclick=download;$('#printPdf').onclick=()=>window.print();$('#newPoster').onclick=()=>{if(confirm('Clear this poster and start again?'))location.reload()};attachDrag();resizeToPreset();
}
function initPaletteOnly(){$$('.swatch').forEach((b,i)=>b.classList.toggle('active',i===state.palette))}
function resizeToPreset(){const p=preset($('#preset').value);canvas.width=p.w;canvas.height=p.h;render()}
function loadUserImage(file){if(!file)return;const img=new Image();img.onload=()=>{state.image=img;state.bg='image';state.imageX=.5;state.imageY=.5;state.imageScale=1;$('#imageScale').value='1';$$('.bg').forEach(x=>x.classList.toggle('active',x.dataset.bg==='image'));render()};img.src=URL.createObjectURL(file)}
function loadStock(key){if(state.stockImages[key])return;const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{state.stockImages[key]=img;render()};img.onerror=()=>{$('#assetStatus').textContent='That stock background could not be loaded. Built-in backgrounds still work offline.'};img.src=stock[key]}
function drawCover(img,x=0,y=0,w=canvas.width,h=canvas.height,scale=1,cx=.5,cy=.5){if(!img)return;const r=Math.max(w/img.width,h/img.height)*scale,dw=img.width*r,dh=img.height*r;ctx.drawImage(img,x+(w-dw)*cx,y+(h-dh)*cy,dw,dh)}
function baseGradient(p){const w=canvas.width,h=canvas.height,g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,p[0]);g.addColorStop(.5,p[1]);g.addColorStop(1,p[0]);ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
function drawWaves(p){const w=canvas.width,h=canvas.height,v=state.variation;ctx.globalAlpha=.3;for(let i=0;i<18;i++){ctx.strokeStyle=i%2?p[2]:p[3];ctx.lineWidth=Math.max(2,w/500);ctx.beginPath();const y=(i/18)*h;ctx.moveTo(-w*.1,y);ctx.bezierCurveTo(w*.25,y+Math.sin(i+v)*h*.18,w*.7,y-Math.cos(i*.7+v)*h*.16,w*1.1,y+Math.sin(i)*h*.12);ctx.stroke()}ctx.globalAlpha=1}
function drawLaser(p){const w=canvas.width,h=canvas.height,cx=w*(.35+(state.variation%7)*.05),cy=h*.3;ctx.save();ctx.globalAlpha=.55;for(let i=0;i<28;i++){ctx.strokeStyle=i%3?p[2]:p[1];ctx.lineWidth=Math.max(2,w*.003);ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo((i/27)*w,h);ctx.stroke()}for(let y=cy;y<h;y+=h*.06){const t=(y-cy)/(h-cy);ctx.strokeStyle=p[3]+'66';ctx.beginPath();ctx.moveTo(cx*(1-t),y);ctx.lineTo(cx+(w-cx)*t,y);ctx.stroke()}ctx.restore()}
function drawTunnel(p){const w=canvas.width,h=canvas.height;ctx.save();ctx.translate(w/2,h/2);for(let i=0;i<16;i++){const t=i/16;ctx.strokeStyle=i%2?p[2]:p[1];ctx.globalAlpha=.12+.5*t;ctx.lineWidth=Math.max(2,w*.005);ctx.strokeRect(-w*.43*t,-h*.43*t,w*.86*t,h*.86*t)}ctx.restore();ctx.globalAlpha=1}
function drawSpeakers(p){const w=canvas.width,h=canvas.height;ctx.save();ctx.globalAlpha=.35;for(let r=0;r<5;r++)for(let c=0;c<4;c++){const x=w*(.14+c*.24),y=h*(.12+r*.2),rad=Math.min(w,h)*.075;ctx.strokeStyle=p[(r+c)%2?2:3];ctx.lineWidth=w*.006;ctx.beginPath();ctx.arc(x,y,rad,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(x,y,rad*.38,0,Math.PI*2);ctx.fillStyle=p[0];ctx.fill();ctx.stroke()}ctx.restore()}
function drawVinyl(p){const w=canvas.width,h=canvas.height,r=Math.min(w,h)*.42,x=w*.7,y=h*.55;ctx.save();ctx.globalAlpha=.72;ctx.fillStyle='#040508';ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();for(let i=1;i<14;i++){ctx.strokeStyle=i%2?p[3]+'22':p[2]+'22';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,r*i/14,0,Math.PI*2);ctx.stroke()}ctx.fillStyle=p[1];ctx.beginPath();ctx.arc(x,y,r*.16,0,Math.PI*2);ctx.fill();ctx.fillStyle='#090b10';ctx.beginPath();ctx.arc(x,y,r*.025,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawTurntables(p){const w=canvas.width,h=canvas.height;ctx.save();ctx.globalAlpha=.72;for(const x of [w*.28,w*.72]){ctx.strokeStyle=p[3];ctx.lineWidth=w*.008;ctx.strokeRect(x-w*.2,h*.35,w*.4,h*.33);ctx.fillStyle='#050609';ctx.beginPath();ctx.arc(x,h*.515,w*.145,0,Math.PI*2);ctx.fill();ctx.strokeStyle=p[2];ctx.beginPath();ctx.arc(x,h*.515,w*.13,0,Math.PI*2);ctx.stroke();ctx.strokeStyle=p[1];ctx.beginPath();ctx.moveTo(x+w*.12,h*.39);ctx.lineTo(x+w*.03,h*.49);ctx.stroke()}ctx.fillStyle=p[3]+'88';ctx.fillRect(w*.46,h*.34,w*.08,h*.37);for(let i=0;i<5;i++){ctx.fillStyle=p[2];ctx.fillRect(w*.475,h*(.38+i*.06),w*.05,h*.012)}ctx.restore()}
function drawSynth(p){const w=canvas.width,h=canvas.height;ctx.save();ctx.globalAlpha=.72;ctx.strokeStyle=p[3];ctx.lineWidth=w*.006;ctx.strokeRect(w*.08,h*.28,w*.84,h*.45);for(let i=0;i<12;i++){const x=w*(.14+(i%6)*.13),y=h*(.36+Math.floor(i/6)*.09);ctx.beginPath();ctx.arc(x,y,w*.022,0,Math.PI*2);ctx.stroke()}const ky=h*.62,kw=w*.055;for(let i=0;i<14;i++){ctx.fillStyle=i%2?p[3]:p[2];ctx.globalAlpha=i%2?.48:.7;ctx.fillRect(w*.1+i*kw,ky,kw*.92,h*.08)}ctx.restore()}
function drawUrban(p){const w=canvas.width,h=canvas.height;ctx.save();ctx.globalAlpha=.55;ctx.fillStyle='#05070a';let x=0;while(x<w){const bw=w*(.06+Math.random()*.08),bh=h*(.18+Math.random()*.45);ctx.fillRect(x,h-bh,bw,bh);for(let wy=h-bh+h*.04;wy<h-h*.04;wy+=h*.055)for(let wx=x+bw*.18;wx<x+bw*.85;wx+=bw*.35){ctx.fillStyle=Math.random()>.65?p[2]+'77':'#111820';ctx.fillRect(wx,wy,bw*.12,h*.015)}ctx.fillStyle='#05070a';x+=bw+w*.015}ctx.globalAlpha=.35;ctx.strokeStyle=p[1];ctx.lineWidth=w*.018;for(let i=0;i<6;i++){ctx.beginPath();ctx.moveTo(w*.05+Math.random()*w*.25,h*(.2+i*.1));ctx.quadraticCurveTo(w*.5,h*(.05+i*.13),w*.9,h*(.18+i*.1));ctx.stroke()}ctx.restore()}
function drawBoombox(p){const w=canvas.width,h=canvas.height;ctx.save();ctx.globalAlpha=.55;ctx.strokeStyle=p[3];ctx.lineWidth=w*.01;ctx.strokeRect(w*.12,h*.32,w*.76,h*.36);ctx.strokeRect(w*.31,h*.22,w*.38,h*.1);for(const x of [w*.3,w*.7]){ctx.beginPath();ctx.arc(x,h*.5,w*.115,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(x,h*.5,w*.05,0,Math.PI*2);ctx.stroke()}ctx.fillStyle=p[2];ctx.fillRect(w*.43,h*.4,w*.14,h*.08);ctx.restore()}
function drawChecker(p){const w=canvas.width,h=canvas.height,s=Math.max(50,w*.09);ctx.save();ctx.globalAlpha=.2;for(let y=0;y<h;y+=s)for(let x=0;x<w;x+=s){ctx.fillStyle=((x/s+y/s)%2)?p[2]:p[3];ctx.fillRect(x,y,s,s)}ctx.restore()}
function drawChrome(p){const w=canvas.width,h=canvas.height;ctx.save();ctx.globalAlpha=.35;for(let i=0;i<20;i++){ctx.strokeStyle=i%2?p[2]:p[3];ctx.lineWidth=w*.01;ctx.beginPath();ctx.ellipse(w*.55,h*.48,w*(.12+i*.025),h*(.04+i*.018),-.35,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawSunset(p){const w=canvas.width,h=canvas.height;ctx.save();const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#100c2c');g.addColorStop(.55,p[1]);g.addColorStop(1,'#06111d');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.fillStyle=p[2];ctx.globalAlpha=.55;ctx.beginPath();ctx.arc(w*.68,h*.36,w*.18,0,Math.PI*2);ctx.fill();ctx.strokeStyle=p[3]+'77';ctx.lineWidth=2;for(let y=h*.62;y<h;y+=h*.045){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.restore()}
function drawXerox(p){const w=canvas.width,h=canvas.height;ctx.save();ctx.fillStyle='#e7e7e2';ctx.fillRect(0,0,w,h);ctx.globalAlpha=.28;for(let i=0;i<90;i++){ctx.fillStyle=Math.random()>.5?'#000':'#444';ctx.fillRect(Math.random()*w,Math.random()*h,w*(.02+Math.random()*.25),Math.max(2,h*.002*Math.random()*5))}ctx.strokeStyle='#000';ctx.lineWidth=w*.016;for(let i=0;i<7;i++){ctx.strokeRect(w*(.04+i*.01),h*(.05+i*.008),w*.88,h*.88)}ctx.restore()}
function drawWarehouse(p){const w=canvas.width,h=canvas.height;ctx.save();ctx.globalAlpha=.4;ctx.strokeStyle=p[3];ctx.lineWidth=w*.004;for(let x=0;x<=w;x+=w*.12){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<=h;y+=h*.08){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}for(let i=0;i<5;i++){ctx.fillStyle='#0008';ctx.fillRect(i*w*.22,h*.22,w*.11,h*.78)}ctx.restore()}
function drawStarfield(p){const w=canvas.width,h=canvas.height;ctx.save();for(let i=0;i<180;i++){const r=Math.random()*w*.004;ctx.fillStyle=Math.random()>.25?p[3]:p[2];ctx.globalAlpha=.15+Math.random()*.75;ctx.beginPath();ctx.arc(Math.random()*w,Math.random()*h,r,0,Math.PI*2);ctx.fill()}ctx.restore()}
function procedural(p){baseGradient(p);const s=state.bgStyle;const builtins={waves:drawWaves,laser:drawLaser,tunnel:drawTunnel,speakers:drawSpeakers,vinyl:drawVinyl,turntable:drawTurntables,synth:drawSynth,urban:drawUrban,boombox:drawBoombox,checker:drawChecker,chrome:drawChrome,sunset:drawSunset,xerox:drawXerox,warehouse:drawWarehouse,starfield:drawStarfield,...extraBackgrounds};(builtins[s]||drawWaves)(p)}
function drawBackground(){const p=palettes[state.palette];if(state.bg==='image'&&state.image)drawCover(state.image,0,0,canvas.width,canvas.height,state.imageScale,state.imageX,state.imageY);else if(stock[state.bg]&&state.stockImages[state.bg])drawCover(state.stockImages[state.bg]);else procedural(p);ctx.fillStyle=`rgba(0,0,0,${state.overlay})`;ctx.fillRect(0,0,canvas.width,canvas.height)}
function drawClipart(){if(state.clipart==='none')return;const p=palettes[state.palette],w=canvas.width,h=canvas.height,x=w*.79,y=h*.69,s=Math.min(w,h)*.18;ctx.save();ctx.globalAlpha=.55;ctx.strokeStyle=p[2];ctx.fillStyle=p[1]+'88';ctx.lineWidth=Math.max(3,w*.007);if(state.clipart==='smiley'){ctx.beginPath();ctx.arc(x,y,s*.55,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(x-s*.19,y-s*.12,s*.045,0,Math.PI*2);ctx.arc(x+s*.19,y-s*.12,s*.045,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x,y+s*.02,s*.28,.15*Math.PI,.85*Math.PI);ctx.stroke()}else if(state.clipart==='vinyl'){ctx.beginPath();ctx.arc(x,y,s*.6,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(x,y,s*.16,0,Math.PI*2);ctx.fill()}else if(state.clipart==='speaker'){for(const yy of [y-s*.3,y+s*.3]){ctx.beginPath();ctx.arc(x,yy,s*.25,0,Math.PI*2);ctx.stroke()}}else if(state.clipart==='turntable'){ctx.strokeRect(x-s*.65,y-s*.45,s*1.3,s*.9);ctx.beginPath();ctx.arc(x-s*.12,y,s*.32,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(x+s*.3,y-s*.28);ctx.lineTo(x+s*.05,y);ctx.stroke()}else if(state.clipart==='synth'){ctx.strokeRect(x-s*.7,y-s*.38,s*1.4,s*.76);for(let i=0;i<8;i++){ctx.fillStyle=i%2?p[3]:p[2];ctx.fillRect(x-s*.62+i*s*.155,y+s*.08,s*.13,s*.2)}for(let i=0;i<5;i++){ctx.beginPath();ctx.arc(x-s*.45+i*s*.23,y-s*.18,s*.045,0,Math.PI*2);ctx.stroke()}}else if(state.clipart==='mic'){ctx.beginPath();ctx.ellipse(x,y-s*.22,s*.16,s*.3,0,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(x,y+s*.08);ctx.lineTo(x,y+s*.55);ctx.moveTo(x-s*.25,y+s*.55);ctx.lineTo(x+s*.25,y+s*.55);ctx.stroke()}else if(state.clipart==='headphones'){ctx.beginPath();ctx.arc(x,y,s*.42,Math.PI,Math.PI*2);ctx.stroke();ctx.strokeRect(x-s*.48,y-s*.02,s*.18,s*.38);ctx.strokeRect(x+s*.3,y-s*.02,s*.18,s*.38)}else if(state.clipart==='spray'){ctx.strokeRect(x-s*.24,y-s*.25,s*.48,s*.75);ctx.strokeRect(x-s*.1,y-s*.42,s*.2,s*.17);ctx.beginPath();ctx.moveTo(x+s*.1,y-s*.34);ctx.lineTo(x+s*.48,y-s*.5);ctx.stroke()}else if(state.clipart==='lightning'){ctx.beginPath();ctx.moveTo(x+s*.15,y-s*.65);ctx.lineTo(x-s*.2,y-s*.05);ctx.lineTo(x+s*.05,y-s*.05);ctx.lineTo(x-s*.15,y+s*.65);ctx.lineTo(x+s*.35,y-s*.15);ctx.lineTo(x+s*.08,y-s*.15);ctx.closePath();ctx.fill()}ctx.restore()}
function wrapText(text,maxWidth,fontSize,font){ctx.font=`900 ${fontSize}px ${font}`;const words=String(text).split(/\s+/),lines=[];let line='';for(const w of words){const test=line?line+' '+w:w;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=w}else line=test}if(line)lines.push(line);return lines}
function drawTextBlock(){const p=palettes[state.palette],w=canvas.width,h=canvas.height,density=state.density==='compact'?.85:state.density==='spacious'?1.15:1,pad=w*.07;let y=h*.09;ctx.textBaseline='top';ctx.fillStyle=p[3];ctx.textAlign='left';if(state.organizer){ctx.font=`700 ${w*.024}px ${state.bodyFont}`;ctx.fillText(state.organizer.toUpperCase(),pad,y);y+=h*.05*density}if(state.title){const size=fontSizeForText(state.title,w*.105,w*.04,18);ctx.font=`900 ${size}px ${state.titleFont}`;ctx.fillStyle=p[3];for(const line of wrapText(state.title.toUpperCase(),w-pad*2,size,state.titleFont).slice(0,3)){ctx.fillText(line,pad,y);y+=size*.9}y+=h*.02}if(state.tagline){ctx.font=`700 ${w*.034}px ${state.bodyFont}`;ctx.fillStyle=p[2];ctx.fillText(state.tagline,pad,y);y+=h*.055*density}const details=compactDetails(state);if(details.length){ctx.font=`700 ${w*.026}px ${state.bodyFont}`;ctx.fillStyle=p[3];ctx.fillText(details.join('  ·  '),pad,y);y+=h*.07*density}const lineup=splitLineup(state.lineup);if(lineup.length){ctx.fillStyle=p[3];const max=Math.min(w*.064,Math.max(w*.028,(h*.34)/(Math.min(12,lineup.length)+1)));ctx.font=`900 ${max}px ${state.titleFont}`;for(const name of lineup.slice(0,20)){ctx.fillText(name,pad,y);y+=max*.96;if(y>h*.78)break}}let bottom=h*.88;ctx.font=`700 ${w*.022}px ${state.bodyFont}`;ctx.fillStyle=p[3];for(const s of [state.extra,state.url].filter(Boolean).reverse()){ctx.fillText(s,pad,bottom);bottom-=h*.04}if(state.url)drawQR(state.url,w*.83,h*.82,w*.11)}
function drawQR(url,x,y,size){if(!window.QRCode||!url)return;const el=$('#qrScratch');el.innerHTML='';new window.QRCode(el,{text:url,width:256,height:256,colorDark:'#000000',colorLight:'#ffffff',correctLevel:window.QRCode.CorrectLevel?.M});const img=el.querySelector('canvas')||el.querySelector('img');if(img){try{ctx.fillStyle='#fff';ctx.fillRect(x-8,y-8,size+16,size+16);ctx.drawImage(img,x,y,size,size)}catch{}}}
function drawTemplateAccents(){const p=palettes[state.palette],t=state.template,w=canvas.width,h=canvas.height;ctx.save();ctx.strokeStyle=p[2];ctx.fillStyle=p[1];ctx.lineWidth=w*.008;if(t==='y2k'||t==='synthwave'){ctx.globalAlpha=.45;for(let i=0;i<5;i++){ctx.beginPath();ctx.ellipse(w*.78,h*.22,w*(.08+i*.035),h*(.03+i*.014),-.4,0,Math.PI*2);ctx.stroke()}}else if(t==='minimal'){ctx.fillRect(w*.06,h*.05,w*.015,h*.9)}else if(t==='retro'){for(let i=0;i<6;i++){ctx.globalAlpha=.18;ctx.fillRect((i%3)*w*.34,Math.floor(i/3)*h*.5,w*.3,h*.44)}}else if(t==='acid'){ctx.globalAlpha=.2;for(let i=0;i<12;i++){ctx.beginPath();ctx.arc(Math.random()*w,Math.random()*h,w*(.03+Math.random()*.12),0,Math.PI*2);ctx.fill()}}else if(t==='luxury'){ctx.globalAlpha=.7;ctx.strokeRect(w*.04,h*.035,w*.92,h*.93)}else if(t==='collage'||t==='hardcore'){ctx.globalAlpha=.5;ctx.setLineDash([w*.01,w*.01]);ctx.strokeRect(w*.05,h*.06,w*.9,h*.86)}else if(t==='hiphop'){ctx.globalAlpha=.4;ctx.strokeRect(w*.055,h*.055,w*.89,h*.89)}ctx.restore()}
function grain(){if(!state.grain)return;const count=Math.floor(canvas.width*canvas.height/9000*state.grain);ctx.save();for(let i=0;i<count;i++){ctx.fillStyle=Math.random()>.5?'#ffffff12':'#00000022';ctx.fillRect(Math.random()*canvas.width,Math.random()*canvas.height,2,2)}ctx.restore()}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);drawBackground();drawTemplateAccents();drawClipart();drawTextBlock();grain()}
function attachDrag(){let dragging=false,lastX=0,lastY=0;canvas.addEventListener('pointerdown',e=>{if(!state.image)return;dragging=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging)return;const r=canvas.getBoundingClientRect();state.imageX=Math.max(0,Math.min(1,state.imageX+(e.clientX-lastX)/r.width));state.imageY=Math.max(0,Math.min(1,state.imageY+(e.clientY-lastY)/r.height));lastX=e.clientX;lastY=e.clientY;render()});canvas.addEventListener('pointerup',()=>dragging=false)}
function download(){render();const type=$('#format').value==='jpg'?'image/jpeg':'image/png',ext=type==='image/jpeg'?'jpg':'png';canvas.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${safeFilename(state.title)}-${$('#preset').value}.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},type,.94)}
init();
