import {PRESETS,TEMPLATES,preset,template,splitLineup,compactDetails,safeFilename,fontSizeForText} from './poster-core.js';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#poster'),ctx=canvas.getContext('2d');
const stock={stock1:'https://images.pexels.com/photos/8448565/pexels-photo-8448565.jpeg?auto=compress&cs=tinysrgb&w=1600',stock2:'https://images.pexels.com/photos/5192299/pexels-photo-5192299.jpeg?auto=compress&cs=tinysrgb&w=1600',stock3:'https://images.pexels.com/photos/10024815/pexels-photo-10024815.jpeg?auto=compress&cs=tinysrgb&w=1600'};
const palettes=[['#07070b','#ff2fb2','#6ef2ff','#ffffff'],['#07090c','#f04d32','#ffcc48','#f5f1e8'],['#0a0a0a','#d7d7d7','#ffffff','#7c8794'],['#080b22','#6d5cff','#35e6ff','#f5f7ff'],['#151006','#ffbd66','#ff6f61','#fff2d7'],['#0b0a10','#b89958','#ece0bd','#ffffff']];
const state={title:'',tagline:'',date:'',time:'',venue:'',city:'',lineup:'',price:'',age:'',organizer:'',extra:'',url:'',template:'neon',palette:0,bg:'procedural',variation:0,titleFont:'Impact',bodyFont:'Arial',overlay:.35,grain:.25,density:'normal',image:null,imageX:.5,imageY:.5,imageScale:1,stockImages:{}};

function init(){
  $('#templates').innerHTML=TEMPLATES.map(t=>`<button class="template ${t.id===state.template?'active':''}" data-template="${t.id}"><strong>${t.name}</strong><span>${t.tags.join(' · ')}</span></button>`).join('');
  $('#palettes').innerHTML=palettes.map((p,i)=>`<button class="swatch ${i===state.palette?'active':''}" data-palette="${i}" style="background:linear-gradient(135deg,${p[1]} 0 50%,${p[2]} 50%)" aria-label="Palette ${i+1}"></button>`).join('');
  $('#preset').innerHTML=Object.entries(PRESETS).map(([k,p])=>`<option value="${k}">${p.label}</option>`).join('');$('#preset').value='instagram';
  $$('[data-field]').forEach(el=>el.addEventListener('input',()=>{state[el.dataset.field]=el.value;render()}));
  $('#templates').onclick=e=>{const b=e.target.closest('[data-template]');if(!b)return;state.template=b.dataset.template;const t=template(state.template);state.titleFont=t.titleFont;state.bodyFont=t.bodyFont;$('#titleFont').value=state.titleFont;$('#bodyFont').value=state.bodyFont;$('.template.active')?.classList.remove('active');b.classList.add('active');$('#templateName').textContent=t.name;render()};
  $('#palettes').onclick=e=>{const b=e.target.closest('[data-palette]');if(!b)return;state.palette=Number(b.dataset.palette);$('.swatch.active')?.classList.remove('active');b.classList.add('active');render()};
  $$('.bg').forEach(b=>b.onclick=()=>{state.bg=b.dataset.bg;$$('.bg').forEach(x=>x.classList.toggle('active',x===b));if(stock[state.bg])loadStock(state.bg);render()});
  $('#imageUpload').onchange=e=>loadUserImage(e.target.files[0]);$('#removeImage').onclick=()=>{state.image=null;state.bg=state.bg==='image'?'procedural':state.bg;render()};$('#centerImage').onclick=()=>{state.imageX=.5;state.imageY=.5;render()};
  $('#modeToggle').onclick=()=>{const a=$('#advanced');a.hidden=!a.hidden;$('#modeToggle').textContent=a.hidden?'Advanced':'Basic'};
  $('#titleFont').onchange=e=>{state.titleFont=e.target.value;render()};$('#bodyFont').onchange=e=>{state.bodyFont=e.target.value;render()};$('#imageScale').oninput=e=>{state.imageScale=Number(e.target.value);render()};$('#overlay').oninput=e=>{state.overlay=Number(e.target.value);render()};$('#grain').oninput=e=>{state.grain=Number(e.target.value);render()};$('#density').onchange=e=>{state.density=e.target.value;render()};
  $('#preset').onchange=()=>resizeToPreset();$('#generate').onclick=()=>{state.variation=(state.variation+1)%7;render()};$('#regenerate').onclick=()=>{state.variation=(state.variation+1)%17;render()};$('#randomColor').onclick=()=>{state.palette=(state.palette+1)%palettes.length;initPaletteOnly();render()};
  $('#download').onclick=download;$('#downloadTop').onclick=download;$('#printPdf').onclick=()=>window.print();$('#newPoster').onclick=()=>{if(confirm('Clear this poster and start again?'))location.reload()};
  attachDrag();resizeToPreset();
}
function initPaletteOnly(){$$('.swatch').forEach((b,i)=>b.classList.toggle('active',i===state.palette))}
function resizeToPreset(){const p=preset($('#preset').value);canvas.width=p.w;canvas.height=p.h;render()}
function loadUserImage(file){if(!file)return;const img=new Image();img.onload=()=>{state.image=img;state.bg='image';state.imageX=.5;state.imageY=.5;state.imageScale=1;$('#imageScale').value='1';$$('.bg').forEach(x=>x.classList.toggle('active',x.dataset.bg==='image'));render()};img.src=URL.createObjectURL(file)}
function loadStock(key){if(state.stockImages[key])return;const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{state.stockImages[key]=img;render()};img.onerror=()=>{};img.src=stock[key]}
function drawCover(img,x=0,y=0,w=canvas.width,h=canvas.height,scale=1,cx=.5,cy=.5){if(!img)return;const r=Math.max(w/img.width,h/img.height)*scale,dw=img.width*r,dh=img.height*r;ctx.drawImage(img,x+(w-dw)*cx,y+(h-dh)*cy,dw,dh)}
function procedural(p,t){const w=canvas.width,h=canvas.height,v=state.variation;const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,p[0]);g.addColorStop(.45,p[1]);g.addColorStop(1,p[0]);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.3;for(let i=0;i<18;i++){ctx.strokeStyle=i%2?p[2]:p[3];ctx.lineWidth=Math.max(2,w/500);ctx.beginPath();const y=(i/18)*h;ctx.moveTo(-w*.1,y);ctx.bezierCurveTo(w*.25,y+Math.sin(i+v)*h*.18,w*.7,y-Math.cos(i*.7+v)*h*.16,w*1.1,y+Math.sin(i)*h*.12);ctx.stroke()}ctx.globalAlpha=1;if(['warehouse','grunge','minimal'].includes(t.id)){ctx.fillStyle='#0008';ctx.fillRect(0,0,w,h);for(let i=0;i<35;i++){ctx.fillStyle=i%2?'#ffffff08':'#00000018';ctx.fillRect(Math.random()*w,Math.random()*h,w*(.1+Math.random()*.3),h*.004)}}}
function drawBackground(){const p=palettes[state.palette],t=template(state.template);if(state.bg==='image'&&state.image)drawCover(state.image,0,0,canvas.width,canvas.height,state.imageScale,state.imageX,state.imageY);else if(stock[state.bg]&&state.stockImages[state.bg])drawCover(state.stockImages[state.bg]);else procedural(p,t);ctx.fillStyle=`rgba(0,0,0,${state.overlay})`;ctx.fillRect(0,0,canvas.width,canvas.height)}
function wrapText(text,maxWidth,fontSize,font){ctx.font=`900 ${fontSize}px ${font}`;const words=String(text).split(/\s+/),lines=[];let line='';for(const w of words){const test=line?line+' '+w:w;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=w}else line=test}if(line)lines.push(line);return lines}
function drawTextBlock(){const p=palettes[state.palette],t=template(state.template),w=canvas.width,h=canvas.height,density=state.density==='compact'?.85:state.density==='spacious'?1.15:1;const pad=w*.07;let y=h*.09;ctx.textBaseline='top';ctx.fillStyle=p[3];ctx.textAlign='left';if(state.organizer){ctx.font=`700 ${w*.024}px ${state.bodyFont}`;ctx.fillText(state.organizer.toUpperCase(),pad,y);y+=h*.05*density}const title=state.title||'';if(title){const size=fontSizeForText(title,w*.105,w*.04,18);ctx.font=`900 ${size}px ${state.titleFont}`;ctx.fillStyle=p[3];const lines=wrapText(title.toUpperCase(),w-pad*2,size,state.titleFont).slice(0,3);for(const line of lines){ctx.fillText(line,pad,y);y+=size*.9}y+=h*.02}if(state.tagline){ctx.font=`700 ${w*.034}px ${state.bodyFont}`;ctx.fillStyle=p[2];ctx.fillText(state.tagline,pad,y);y+=h*.055*density}const details=compactDetails(state);if(details.length){ctx.font=`700 ${w*.026}px ${state.bodyFont}`;ctx.fillStyle=p[3];ctx.fillText(details.join('  ·  '),pad,y);y+=h*.07*density}const lineup=splitLineup(state.lineup);if(lineup.length){ctx.fillStyle=p[3];const max=Math.min(w*.064,Math.max(w*.028,(h*.34)/(Math.min(12,lineup.length)+1)));ctx.font=`900 ${max}px ${state.titleFont}`;for(const name of lineup.slice(0,20)){ctx.fillText(name,pad,y);y+=max*.96;if(y>h*.78)break}}let bottom=h*.88;ctx.font=`700 ${w*.022}px ${state.bodyFont}`;ctx.fillStyle=p[3];for(const s of [state.extra,state.url].filter(Boolean).reverse()){ctx.fillText(s,pad,bottom);bottom-=h*.04}if(state.url)drawQR(state.url,w*.83,h*.82,w*.11)}
function drawQR(url,x,y,size){if(!window.QRCode||!url)return;const el=$('#qrScratch');el.innerHTML='';new window.QRCode(el,{text:url,width:256,height:256,colorDark:'#000000',colorLight:'#ffffff',correctLevel:window.QRCode.CorrectLevel?.M});const img=el.querySelector('canvas')||el.querySelector('img');if(img){try{ctx.fillStyle='#fff';ctx.fillRect(x-8,y-8,size+16,size+16);ctx.drawImage(img,x,y,size,size)}catch{}}}
function drawTemplateAccents(){const p=palettes[state.palette],t=state.template,w=canvas.width,h=canvas.height;ctx.save();ctx.strokeStyle=p[2];ctx.fillStyle=p[1];ctx.lineWidth=w*.008;if(t==='y2k'){ctx.globalAlpha=.45;for(let i=0;i<5;i++){ctx.beginPath();ctx.ellipse(w*.78,h*.22,w*(.08+i*.035),h*(.03+i*.014),-.4,0,Math.PI*2);ctx.stroke()}}else if(t==='minimal'){ctx.fillRect(w*.06,h*.05,w*.015,h*.9)}else if(t==='retro'){for(let i=0;i<6;i++){ctx.globalAlpha=.18;ctx.fillRect((i%3)*w*.34,Math.floor(i/3)*h*.5,w*.3,h*.44)}}else if(t==='acid'){ctx.globalAlpha=.2;for(let i=0;i<12;i++){ctx.beginPath();ctx.arc(Math.random()*w,Math.random()*h,w*(.03+Math.random()*.12),0,Math.PI*2);ctx.fill()}}else if(t==='luxury'){ctx.globalAlpha=.7;ctx.strokeRect(w*.04,h*.035,w*.92,h*.93)}else if(t==='collage'){ctx.globalAlpha=.5;ctx.setLineDash([w*.01,w*.01]);ctx.strokeRect(w*.05,h*.06,w*.9,h*.86)}ctx.restore()}
function grain(){if(!state.grain)return;const count=Math.floor(canvas.width*canvas.height/9000*state.grain);ctx.save();for(let i=0;i<count;i++){ctx.fillStyle=Math.random()>.5?'#ffffff12':'#00000022';ctx.fillRect(Math.random()*canvas.width,Math.random()*canvas.height,2,2)}ctx.restore()}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);drawBackground();drawTemplateAccents();drawTextBlock();grain()}
function attachDrag(){let dragging=false,lastX=0,lastY=0;canvas.addEventListener('pointerdown',e=>{if(!state.image)return;dragging=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging)return;const r=canvas.getBoundingClientRect();state.imageX=Math.max(0,Math.min(1,state.imageX+(e.clientX-lastX)/r.width));state.imageY=Math.max(0,Math.min(1,state.imageY+(e.clientY-lastY)/r.height));lastX=e.clientX;lastY=e.clientY;render()});canvas.addEventListener('pointerup',()=>dragging=false)}
function download(){render();const type=$('#format').value==='jpg'?'image/jpeg':'image/png';const ext=type==='image/jpeg'?'jpg':'png';canvas.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${safeFilename(state.title)}-${$('#preset').value}.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},type,.94)}
init();
