function rng(seed){let x=(seed|0)+0x6d2b79f5;return()=>{x=Math.imul(x^(x>>>15),x|1);x^=x+Math.imul(x^(x>>>7),x|61);return((x^(x>>>14))>>>0)/4294967296}}
export function createBackgroundRenderers(ctx,canvas,state){
 const dims=()=>[canvas.width,canvas.height],rand=()=>rng((state.variation+1)*2654435761);
 function acidblobs(p){const[w,h]=dims(),r=rand();ctx.save();ctx.globalAlpha=.42;for(let i=0;i<14;i++){const x=r()*w,y=r()*h,rad=Math.min(w,h)*(.05+r()*.16);ctx.fillStyle=i%2?p[1]:p[2];ctx.beginPath();for(let a=0;a<=Math.PI*2+.01;a+=Math.PI/8){const rr=rad*(.72+r()*.5),px=x+Math.cos(a)*rr,py=y+Math.sin(a)*rr;if(a===0)ctx.moveTo(px,py);else ctx.lineTo(px,py)}ctx.closePath();ctx.fill()}ctx.restore()}
 function oscilloscope(p){const[w,h]=dims();ctx.save();ctx.globalAlpha=.42;ctx.strokeStyle=p[3]+'55';ctx.lineWidth=Math.max(1,w*.0015);for(let x=0;x<w;x+=w*.08){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=h*.06){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}for(let band=0;band<5;band++){ctx.strokeStyle=band%2?p[2]:p[1];ctx.globalAlpha=.38+.08*band;ctx.lineWidth=Math.max(2,w*.004);ctx.beginPath();for(let x=0;x<=w;x+=w/180){const t=x/w,y=h*(.16+band*.17)+Math.sin(t*Math.PI*(8+band*3)+state.variation*.7)*h*(.035+band*.006)+Math.sin(t*Math.PI*35)*h*.008;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()}ctx.restore()}
 function equalizer(p){const[w,h]=dims(),r=rand(),cols=28,gap=w*.008,bw=(w-gap*(cols+1))/cols;ctx.save();ctx.globalAlpha=.5;for(let i=0;i<cols;i++){const bars=3+Math.floor(r()*15),x=gap+i*(bw+gap);for(let b=0;b<bars;b++){ctx.fillStyle=(i+b)%3===0?p[1]:(i+b)%3===1?p[2]:p[3];ctx.fillRect(x,h*.82-b*h*.038,bw,h*.024)}}ctx.restore()}
 function circuitry(p){const[w,h]=dims(),r=rand();ctx.save();ctx.globalAlpha=.38;ctx.lineWidth=Math.max(2,w*.003);for(let i=0;i<32;i++){let x=r()*w,y=r()*h;ctx.strokeStyle=i%2?p[2]:p[3];ctx.beginPath();ctx.moveTo(x,y);for(let s=0;s<5;s++){if(s%2)x=Math.max(0,Math.min(w,x+(r()-.5)*w*.26));else y=Math.max(0,Math.min(h,y+(r()-.5)*h*.22));ctx.lineTo(x,y)}ctx.stroke();ctx.fillStyle=p[1];ctx.beginPath();ctx.arc(x,y,w*.008,0,Math.PI*2);ctx.fill()}ctx.restore()}
 function cybergrid(p){const[w,h]=dims(),hy=h*.42;ctx.save();ctx.globalAlpha=.45;ctx.strokeStyle=p[2];ctx.lineWidth=Math.max(1,w*.0025);for(let i=-12;i<=12;i++){ctx.beginPath();ctx.moveTo(w/2,hy);ctx.lineTo(w/2+i*w*.11,h);ctx.stroke()}for(let i=0;i<18;i++){const t=i/18,y=hy+(h-hy)*t*t;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.fillStyle=p[1]+'66';ctx.fillRect(0,hy-h*.012,w,h*.024);ctx.restore()}
 function vortex(p){const[w,h]=dims(),cx=w*.52,cy=h*.48;ctx.save();ctx.globalAlpha=.5;ctx.lineWidth=Math.max(2,w*.003);for(let arm=0;arm<7;arm++){ctx.strokeStyle=arm%2?p[1]:p[2];ctx.beginPath();for(let i=0;i<160;i++){const t=i/159,a=t*Math.PI*5+arm*Math.PI*2/7+state.variation*.12,rad=t*Math.min(w,h)*.58,x=cx+Math.cos(a)*rad,y=cy+Math.sin(a)*rad;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()}ctx.restore()}
 function halftone(p){const[w,h]=dims(),step=Math.max(22,w*.04);ctx.save();ctx.globalAlpha=.35;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const d=Math.hypot(x-w*.65,y-h*.38)/Math.hypot(w,h),rad=step*(.08+.42*(1-Math.min(1,d)));ctx.fillStyle=((x/step+y/step)|0)%2?p[2]:p[3];ctx.beginPath();ctx.arc(x,y,rad,0,Math.PI*2);ctx.fill()}ctx.restore()}
 function glitch(p){const[w,h]=dims(),r=rand();ctx.save();ctx.globalAlpha=.38;for(let i=0;i<80;i++){const y=r()*h,hh=h*(.002+r()*.025),x=(r()-.15)*w,ww=w*(.08+r()*.55);ctx.fillStyle=i%3===0?p[1]:i%3===1?p[2]:p[3];ctx.fillRect(x,y,ww,hh)}ctx.globalAlpha=.18;for(let i=0;i<16;i++){const y=r()*h;ctx.fillStyle='#fff';ctx.fillRect(0,y,w,h*.002)}ctx.restore()}
 function cassette(p){const[w,h]=dims(),x=w*.12,y=h*.3,cw=w*.76,ch=h*.38;ctx.save();ctx.globalAlpha=.58;ctx.strokeStyle=p[3];ctx.fillStyle=p[0]+'cc';ctx.lineWidth=w*.008;ctx.fillRect(x,y,cw,ch);ctx.strokeRect(x,y,cw,ch);ctx.fillStyle=p[1]+'77';ctx.fillRect(x+cw*.08,y+ch*.12,cw*.84,ch*.2);for(const cx of [x+cw*.32,x+cw*.68]){ctx.beginPath();ctx.arc(cx,y+ch*.55,cw*.12,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(cx,y+ch*.55,cw*.045,0,Math.PI*2);ctx.fillStyle=p[2];ctx.fill()}ctx.beginPath();ctx.moveTo(x+cw*.24,y+ch*.86);ctx.lineTo(x+cw*.76,y+ch*.86);ctx.lineTo(x+cw*.67,y+ch*.68);ctx.lineTo(x+cw*.33,y+ch*.68);ctx.closePath();ctx.stroke();ctx.restore()}
 function drummachine(p){const[w,h]=dims(),x=w*.08,y=h*.22,cw=w*.84,ch=h*.54;ctx.save();ctx.globalAlpha=.58;ctx.fillStyle='#05070b99';ctx.strokeStyle=p[3];ctx.lineWidth=w*.006;ctx.fillRect(x,y,cw,ch);ctx.strokeRect(x,y,cw,ch);for(let row=0;row<4;row++)for(let col=0;col<8;col++){ctx.fillStyle=(col+row+state.variation)%5===0?p[1]:p[2]+'88';ctx.fillRect(x+cw*(.08+col*.105),y+ch*(.42+row*.105),cw*.075,ch*.065)}for(let i=0;i<8;i++){ctx.beginPath();ctx.arc(x+cw*(.09+i*.105),y+ch*.22,cw*.026,0,Math.PI*2);ctx.stroke()}ctx.restore()}
 function flyers(p){const[w,h]=dims(),r=rand();ctx.save();ctx.globalAlpha=.32;for(let i=0;i<13;i++){const fw=w*(.22+r()*.34),fh=h*(.16+r()*.28),x=r()*(w-fw),y=r()*(h-fh);ctx.save();ctx.translate(x+fw/2,y+fh/2);ctx.rotate((r()-.5)*.45);ctx.fillStyle=i%3===0?p[1]:i%3===1?p[2]:p[3];ctx.fillRect(-fw/2,-fh/2,fw,fh);ctx.fillStyle=p[0];for(let l=0;l<5;l++)ctx.fillRect(-fw*.38,-fh*.3+l*fh*.13,fw*(.25+r()*.5),Math.max(2,fh*.025));ctx.restore()}ctx.restore()}
 function memphis(p){const[w,h]=dims(),r=rand();ctx.save();ctx.globalAlpha=.42;for(let i=0;i<34;i++){const x=r()*w,y=r()*h,s=Math.min(w,h)*(.025+r()*.09);ctx.strokeStyle=i%2?p[2]:p[3];ctx.fillStyle=i%3===0?p[1]+'99':p[2]+'77';ctx.lineWidth=Math.max(2,w*.004);if(i%4===0){ctx.fillRect(x-s,y-s,s*2,s*2)}else if(i%4===1){ctx.beginPath();ctx.arc(x,y,s,0,Math.PI*2);ctx.stroke()}else if(i%4===2){ctx.beginPath();ctx.moveTo(x,y-s);ctx.lineTo(x+s,y+s);ctx.lineTo(x-s,y+s);ctx.closePath();ctx.fill()}else{ctx.beginPath();ctx.moveTo(x-s,y);ctx.quadraticCurveTo(x,y-s,x+s,y);ctx.quadraticCurveTo(x,y+s,x-s,y);ctx.stroke()}}ctx.restore()}
 return{acidblobs,oscilloscope,equalizer,circuitry,cybergrid,vortex,halftone,glitch,cassette,drummachine,flyers,memphis};
}
