function rng(seed){let x=(seed|0)+0x6d2b79f5;return()=>{x=Math.imul(x^(x>>>15),x|1);x^=x+Math.imul(x^(x>>>7),x|61);return((x^(x>>>14))>>>0)/4294967296}}
export function createBackgroundRenderers(ctx,canvas,state){
 const dims=()=>[canvas.width,canvas.height],rand=()=>rng((state.variation+1)*2654435761);
 function acidblobs(p){const[w,h]=dims(),r=rand();ctx.save();ctx.globalAlpha=.42;for(let i=0;i<14;i++){const x=r()*w,y=r()*h,rad=Math.min(w,h)*(.05+r()*.16);ctx.fillStyle=i%2?p[1]:p[2];ctx.beginPath();for(let a=0;a<=Math.PI*2+.01;a+=Math.PI/8){const rr=rad*(.72+r()*.5),px=x+Math.cos(a)*rr,py=y+Math.sin(a)*rr;if(a===0)ctx.moveTo(px,py);else ctx.lineTo(px,py)}ctx.closePath();ctx.fill()}ctx.restore()}
 function oscilloscope(p){const[w,h]=dims();ctx.save();ctx.globalAlpha=.42;ctx.strokeStyle=p[3]+'55';ctx.lineWidth=Math.max(1,w*.0015);for(let x=0;x<w;x+=w*.08){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=h*.06){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}for(let band=0;band<5;band++){ctx.strokeStyle=band%2?p[2]:p[1];ctx.globalAlpha=.38+.08*band;ctx.lineWidth=Math.max(2,w*.004);ctx.beginPath();for(let x=0;x<=w;x+=w/180){const t=x/w,y=h*(.16+band*.17)+Math.sin(t*Math.PI*(8+band*3)+state.variation*.7)*h*(.035+band*.006)+Math.sin(t*Math.PI*35)*h*.008;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()}ctx.restore()}
 function equalizer(p){const[w,h]=dims(),r=rand(),cols=28,gap=w*.008,bw=(w-gap*(cols+1))/cols;ctx.save();ctx.globalAlpha=.5;for(let i=0;i<cols;i++){const bars=3+Math.floor(r()*15),x=gap+i*(bw+gap);for(let b=0;b<bars;b++){ctx.fillStyle=(i+b)%3===0?p[1]:(i+b)%3===1?p[2]:p[3];ctx.fillRect(x,h*.82-b*h*.038,bw,h*.024)}}ctx.restore()}
 function circuitry(p){const[w,h]=dims(),r=rand();ctx.save();ctx.globalAlpha=.38;ctx.lineWidth=Math.max(2,w*.003);for(let i=0;i<32;i++){let x=r()*w,y=r()*h;ctx.strokeStyle=i%2?p[2]:p[3];ctx.beginPath();ctx.moveTo(x,y);for(let s=0;s<5;s++){if(s%2)x=Math.max(0,Math.min(w,x+(r()-.5)*w*.26));else y=Math.max(0,Math.min(h,y+(r()-.5)*h*.22));ctx.lineTo(x,y)}ctx.stroke();ctx.fillStyle=p[1];ctx.beginPath();ctx.arc(x,y,w*.008,0,Math.PI*2);ctx.fill()}ctx.restore()}
 function cybergrid(p){const[w,h]=dims(),hy=h*.42;ctx.save();ctx.globalAlpha=.45;ctx.strokeStyle=p[2];ctx.lineWidth=Math.max(1,w*.0025);for(let i=-12;i<=12;i++){ctx.beginPath();ctx.moveTo(w/2,hy);ctx.lineTo(w/2+i*w*.11,h);ctx.stroke()}for(let i=0;i<18;i++){const t=i/18,y=hy+(h-hy)*t*t;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.fillStyle=p[1]+'66';ctx.fillRect(0,hy-h*.012,w,h*.024);ctx.restore()}
 function vortex(p){const[w,h]=dims(),cx=w*.52,cy=h*.48;ctx.save();ctx.globalAlpha=.5;ctx.lineWidth=Math.max(2,w*.003);for(let arm=0;arm<7;arm++){ctx.strokeStyle=arm%2?p[1]:p[2];ctx.beginPath();for(let i=0;i<160;i++){const t=i/159,a=t*Math.PI*5+arm*Math.PI*2/7+state.variation*.12,rad=t*Math.min(w,h)*.58,x=cx+Math.cos(a)*rad,y=cy+Math.sin(a)*rad;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()}ctx.restore()}
 function halftone(p){const[w,h]=dims(),step=Math.max(22,w*.04);ctx.save();ctx.globalAlpha=.35;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const d=Math.hypot(x-w*.65,y-h*.38)/Math.hypot(w,h),rad=step*(.08+.42*(1-Math.min(1,d)));ctx.fillStyle=((x/step+y/step)|0)%2?p[2]:p[3];ctx.beginPath();ctx.arc(x,y,rad,0,Math.PI*2);ctx.fill()}ctx.restore()}
 function glitch(p){const[w,h]=dims(),r=rand();ctx.save();ctx.globalAlpha=.38;for(let i=0;i<80;i++){const y=r()*h,hh=h*(.002+r()*.025),x=(r()-.15)*w,ww=w*(.08+r()*.55);ctx.fillStyle=i%3===0?p[1]:i%3===1?p[2]:p[3];ctx.fillRect(x,y,ww,hh)}ctx.globalAlpha=.18;for(let i=0;i<16;i++){const y=r()*h;ctx.fillStyle='#fff';ctx.fillRect(0,y,w,h*.002)}ctx.restore()}
 function cassette(p){const[w,h]=dims(),x=w*.12,y=h*.3,cw=w*.76,ch=h*.38;ctx.save();ctx.globalAlpha=.58;ctx.strokeStyle=p[3];ctx.fillStyle=p[0]+'cc';ctx.lineWidth=w*.008;ctx.fillRect(x,y,cw,ch);ctx.strokeRect(x,y,cw,ch);ctx.fillStyle=p[1]+'77';ctx.fillRect(x+cw*.08,y+ch*.12,cw*.84,ch*.2);for(const cx of [x+cw*.32,x+cw*.68]){ctx.beginPath();ctx.arc(cx,y+ch*.55,cw*.12,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(cx,y+ch*.55,cw*.045,0,Math.PI*2);ctx.fillStyle=p[2];ctx.fill()}ctx.beginPath();ctx.moveTo(x+cw*.24,y+ch*.86);ctx.lineTo(x+cw*.76,y+ch*.86);ctx.lineTo(x+cw*.67,y+ch*.68);ctx.lineTo(x+cw*.33,y+ch*.68);ctx.closePath();ctx.stroke();ctx.restore()}
 function drummachine(p){const[w,h]=dims(),x=w*.08,y=h*.22,cw=w*.84,ch=h*.54;ctx.save();ctx.globalAlpha=.58;ctx.fillStyle='#05070b99';ctx.strokeStyle=p[3];ctx.lineWidth=w*.006;ctx.fillRect(x,y,cw,ch);ctx.strokeRect(x,y,cw,ch);for(let row=0;row<4;row++)for(let col=0;col<8;col++){ctx.fillStyle=(col+row+state.variation)%5===0?p[1]:p[2]+'88';ctx.fillRect(x+cw*(.08+col*.105),y+ch*(.42+row*.105),cw*.075,ch*.065)}for(let i=0;i<8;i++){ctx.beginPath();ctx.arc(x+cw*(.09+i*.105),y+ch*.22,cw*.026,0,Math.PI*2);ctx.stroke()}ctx.restore()}
 function flyers(p){const[w,h]=dims(),r=rand();ctx.save();ctx.globalAlpha=.32;for(let i=0;i<13;i++){const fw=w*(.22+r()*.34),fh=h*(.16+r()*.28),x=r()*(w-fw),y=r()*(h-fh);ctx.save();ctx.translate(x+fw/2,y+fh/2);ctx.rotate((r()-.5)*.45);ctx.fillStyle=i%3===0?p[1]:i%3===1?p[2]:p[3];ctx.fillRect(-fw/2,-fh/2,fw,fh);ctx.fillStyle=p[0];for(let l=0;l<5;l++)ctx.fillRect(-fw*.38,-fh*.3+l*fh*.13,fw*(.25+r()*.5),Math.max(2,fh*.025));ctx.restore()}ctx.restore()}
 function memphis(p){const[w,h]=dims(),r=rand();ctx.save();ctx.globalAlpha=.42;for(let i=0;i<34;i++){const x=r()*w,y=r()*h,s=Math.min(w,h)*(.025+r()*.09);ctx.strokeStyle=i%2?p[2]:p[3];ctx.fillStyle=i%3===0?p[1]+'99':p[2]+'77';ctx.lineWidth=Math.max(2,w*.004);if(i%4===0){ctx.fillRect(x-s,y-s,s*2,s*2)}else if(i%4===1){ctx.beginPath();ctx.arc(x,y,s,0,Math.PI*2);ctx.stroke()}else if(i%4===2){ctx.beginPath();ctx.moveTo(x,y-s);ctx.lineTo(x+s,y+s);ctx.lineTo(x-s,y+s);ctx.closePath();ctx.fill()}else{ctx.beginPath();ctx.moveTo(x-s,y);ctx.quadraticCurveTo(x,y-s,x+s,y);ctx.quadraticCurveTo(x,y+s,x-s,y);ctx.stroke()}}ctx.restore()}
 function lasergrid(p){const[w,h]=dims(),r=rand();ctx.save();ctx.globalAlpha=.48;const sx=w/16,sy=h/9;for(let i=0;i<16;i++)for(let j=0;j<9;j++){ctx.strokeStyle=((i+j+state.variation)%2)?p[1]:p[2];ctx.lineWidth=w*.0015;ctx.strokeRect(i*sx,j*sy,sx,sy)}for(let i=0;i<6;i++){ctx.strokeStyle=p[3];ctx.globalAlpha=.35+i*.08;ctx.lineWidth=Math.max(2,w*.005);ctx.beginPath();const y=h*(.15+i*.14);ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.restore()}
 function neonwaves(p){const[w,h]=dims(),r=rand();ctx.save();ctx.globalAlpha=.5;for(let i=0;i<12;i++){ctx.strokeStyle=i%2?p[1]:p[2];ctx.lineWidth=Math.max(3,w*.008);ctx.beginPath();const sy=h*(.08+i*.08),amp=h*(.05+r()*.08),freq=2+r()*.8;for(let x=0;x<=w;x+=w*.02){const y=sy+Math.sin(x/w*Math.PI*freq+state.variation*.15)*amp;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()}ctx.restore()}
 function strobestripes(p){const[w,h]=dims();ctx.save();const stripe=w*.08,speed=state.variation%8;for(let i=0;i<30;i++){ctx.fillStyle=(i%2===0)?p[1]:p[2];ctx.globalAlpha=(i%2)?.6:.3;ctx.fillRect((i*stripe+speed*w*.02)%w-stripe,0,stripe,h)}ctx.restore()}
 function synthwavesun(p){const[w,h]=dims();ctx.save();const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#16213e');g.addColorStop(.4,p[1]+'88');g.addColorStop(1,'#0f3460');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.fillStyle=p[2];ctx.globalAlpha=.7;ctx.beginPath();ctx.arc(w*.52,h*.35,w*.22,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.35;for(let i=1;i<8;i++){ctx.strokeStyle=p[3];ctx.lineWidth=w*.004;ctx.beginPath();ctx.ellipse(w*.52,h*.35,w*(.22+i*.04),h*(.08+i*.012),0,0,Math.PI*2);ctx.stroke()}ctx.restore()}
 function plasma(p){const[w,h]=dims(),r=rand();ctx.save();ctx.globalAlpha=.55;for(let i=0;i<200;i++){const x=r()*w,y=r()*h,rad=Math.min(w,h)*(.005+r()*.04);ctx.fillStyle=((i%3)?p[1]:p[2])+(Math.floor(r()*16)).toString(16).padStart(2,'0');ctx.beginPath();ctx.arc(x,y,rad,0,Math.PI*2);ctx.fill()}ctx.restore()}
 function soundwaves(p){const[w,h]=dims();ctx.save();ctx.globalAlpha=.42;const cx=w*.15,cy=h*.5;for(let i=0;i<12;i++){ctx.strokeStyle=i%2?p[1]:p[2];ctx.globalAlpha=.5-i*.035;ctx.lineWidth=Math.max(2,w*.005);ctx.beginPath();ctx.arc(cx,cy,w*(.08+i*.07),0,Math.PI*2);ctx.stroke()}for(let i=0;i<25;i++){ctx.strokeStyle=p[3];ctx.globalAlpha=.28;ctx.lineWidth=1;ctx.beginPath();const x=cx+w*(.08+i*.028),y=cy+Math.sin(i+state.variation*.1)*h*.3;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();ctx.restore()}
 function checkerwarp(p){const[w,h]=dims(),size=Math.max(40,w*.06),speed=state.variation%12;ctx.save();ctx.globalAlpha=.38;ctx.translate(w/2,h/2);ctx.scale(1+speed*.02,1+speed*.02);ctx.translate(-w/2,-h/2);for(let y=-size;y<h+size;y+=size)for(let x=-size;x<w+size;x+=size){ctx.fillStyle=((x/size+y/size)%2)?p[1]:p[2];ctx.fillRect(x,y,size,size)}ctx.restore()}
 function holographic(p){const[w,h]=dims(),r=rand();ctx.save();const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,p[1]+'33');g.addColorStop(.5,p[2]+'44');g.addColorStop(1,p[3]+'33');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.28;for(let i=0;i<150;i++){ctx.strokeStyle=r()>.5?p[1]:p[2];ctx.lineWidth=r()>0.7?3:1;ctx.beginPath();const x1=r()*w,y1=r()*h,x2=x1+r()*w*.2-w*.1,y2=y1+r()*h*.2-h*.1;ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}ctx.restore()}
 function acidsmileys(p){const[w,h]=dims(),r=rand();ctx.save();ctx.globalAlpha=.45;for(let i=0;i<9;i++){const x=r()*w,y=r()*h,s=Math.min(w,h)*(.04+r()*.08);ctx.strokeStyle=i%2?p[1]:p[2];ctx.lineWidth=Math.max(2,w*.005);ctx.beginPath();ctx.arc(x,y,s,0,Math.PI*2);ctx.stroke();ctx.fillStyle=i%3?p[2]:p[3];ctx.beginPath();ctx.arc(x-s*.25,y-s*.2,s*.15,0,Math.PI*2);ctx.arc(x+s*.25,y-s*.2,s*.15,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x,y+s*.1,s*.22,.2*Math.PI,.8*Math.PI);ctx.stroke()}ctx.restore()}
 // Fractal backgrounds
 function mandelbrot(p){const[w,h]=dims();const size=Math.min(w,h);const canvas2=document.createElement('canvas');canvas2.width=800;canvas2.height=800;const c2=canvas2.getContext('2d');const id=c2.createImageData(800,800);const data=id.data;const zoom=1+state.variation*.15,cx=-0.7+Math.sin(state.variation*.08)*.3,cy=0+Math.cos(state.variation*.08)*.2;for(let y=0;y<800;y++)for(let x=0;x<800;x++){let zr=0,zi=0,cr=(x/800-0.5)*2.5/zoom+cx,ci=(y/800-0.5)*2.5/zoom+cy;let it=0;for(;it<255&&zr*zr+zi*zi<4;it++){const zr2=zr*zr-zi*zi+cr,zi2=2*zr*zi+ci;zr=zr2;zi=zi2}const col=it<255?(it%3===0?p[1]:it%3===1?p[2]:p[3]):p[0];const off=(y*800+x)*4;const c=parseInt(col.slice(1),16);data[off]=(c>>16)&255;data[off+1]=(c>>8)&255;data[off+2]=c&255;data[off+3]=255}c2.putImageData(id,0,0);ctx.globalAlpha=.62;ctx.drawImage(canvas2,0,0,w,h);ctx.restore()}
 function julia(p){const[w,h]=dims();const canvas2=document.createElement('canvas');canvas2.width=800;canvas2.height=800;const c2=canvas2.getContext('2d');const id=c2.createImageData(800,800);const data=id.data;const jcrReal=-0.8+Math.sin(state.variation*.1)*.15,jcrImag=0.156+Math.cos(state.variation*.08)*.1;for(let y=0;y<800;y++)for(let x=0;x<800;x++){let zr=(x/800-0.5)*2.8,zi=(y/800-0.5)*2.8;let it=0;for(;it<255&&zr*zr+zi*zi<4;it++){const zr2=zr*zr-zi*zi+jcrReal,zi2=2*zr*zi+jcrImag;zr=zr2;zi=zi2}const col=it<255?(it%3===0?p[2]:it%3===1?p[1]:p[3]):p[0];const off=(y*800+x)*4;const c=parseInt(col.slice(1),16);data[off]=(c>>16)&255;data[off+1]=(c>>8)&255;data[off+2]=c&255;data[off+3]=255}c2.putImageData(id,0,0);ctx.globalAlpha=.68;ctx.drawImage(canvas2,0,0,w,h);ctx.restore()}
 function burningjulia(p){const[w,h]=dims();const canvas2=document.createElement('canvas');canvas2.width=800;canvas2.height=800;const c2=canvas2.getContext('2d');const id=c2.createImageData(800,800);const data=id.data;const jcrReal=-0.162+Math.sin(state.variation*.12)*.08,jcrImag=1.04+Math.cos(state.variation*.09)*.05;for(let y=0;y<800;y++)for(let x=0;x<800;x++){let zr=(x/800-0.5)*3,zi=(y/800-0.5)*3;let it=0;for(;it<255&&zr*zr+zi*zi<4;it++){const zr2=zr*zr-zi*zi+jcrReal,zi2=2*zr*zi+jcrImag;zr=zr2;zi=zi2}const col=it<64?p[1]:it<128?p[2]:it<192?p[3]:'#ff6600';const off=(y*800+x)*4;const c=parseInt(col.slice(1),16);data[off]=(c>>16)&255;data[off+1]=(c>>8)&255;data[off+2]=c&255;data[off+3]=255}c2.putImageData(id,0,0);ctx.globalAlpha=.72;ctx.drawImage(canvas2,0,0,w,h);ctx.restore()}
 function tricorn(p){const[w,h]=dims();const canvas2=document.createElement('canvas');canvas2.width=600;canvas2.height=600;const c2=canvas2.getContext('2d');const id=c2.createImageData(600,600);const data=id.data;const zoom=0.8+state.variation*.12;for(let y=0;y<600;y++)for(let x=0;x<600;x++){let zr=0,zi=0,cr=(x/600-0.5)*3.8/zoom-0.27,ci=(y/600-0.5)*3.8/zoom;let it=0;for(;it<200&&zr*zr+zi*zi<4;it++){const zr2=zr*zr-zi*zi+cr,zi2=-2*zr*zi+ci;zr=zr2;zi=zi2}const col=it<67?p[1]:it<133?p[2]:p[3];const off=(y*600+x)*4;const c=parseInt(col.slice(1),16);data[off]=(c>>16)&255;data[off+1]=(c>>8)&255;data[off+2]=c&255;data[off+3]=255}c2.putImageData(id,0,0);ctx.globalAlpha=.65;ctx.drawImage(canvas2,0,0,w,h);ctx.restore()}
 function nova(p){const[w,h]=dims();const canvas2=document.createElement('canvas');canvas2.width=700;canvas2.height=700;const c2=canvas2.getContext('2d');const id=c2.createImageData(700,700);const data=id.data;const zoom=1.2+state.variation*.1;for(let y=0;y<700;y++)for(let x=0;x<700;x++){let zr=0,zi=0,cr=(x/700-0.5)*2.5/zoom-0.3,ci=(y/700-0.5)*2.5/zoom+0.02;let it=0;for(;it<180&&zr*zr+zi*zi<16;it++){const zr2=zr*zr-zi*zi+cr/(1+zr*zr+zi*zi),zi2=2*zr*zi+ci/(1+zr*zr+zi*zi);zr=zr2;zi=zi2}const col=it<45?p[3]:it<90?p[2]:it<135?p[1]:p[0];const off=(y*700+x)*4;const c=parseInt(col.slice(1),16);data[off]=(c>>16)&255;data[off+1]=(c>>8)&255;data[off+2]=c&255;data[off+3]=255}c2.putImageData(id,0,0);ctx.globalAlpha=.58;ctx.drawImage(canvas2,0,0,w,h);ctx.restore()}
 function phoenixjulia(p){const[w,h]=dims();const canvas2=document.createElement('canvas');canvas2.width=750;canvas2.height=750;const c2=canvas2.getContext('2d');const id=c2.createImageData(750,750);const data=id.data;const re=-0.5,im=0;for(let y=0;y<750;y++)for(let x=0;x<750;x++){let zr=0,zi=0,cr=(x/750-0.5)*2/0.7,ci=(y/750-0.5)*2/0.7;let it=0;for(;it<200&&zr*zr+zi*zi<100;it++){const zr2=zr*zr-zi*zi+re*(zi-zr)+re,zi2=2*zr*zi+im*(zi+zr)+im;zr=zr2;zi=zi2}const col=it<50?p[2]:it<100?p[1]:it<150?p[3]:'#ff00ff';const off=(y*750+x)*4;const c=parseInt(col.slice(1),16);data[off]=(c>>16)&255;data[off+1]=(c>>8)&255;data[off+2]=c&255;data[off+3]=255}c2.putImageData(id,0,0);ctx.globalAlpha=.64;ctx.drawImage(canvas2,0,0,w,h);ctx.restore()}
 function juliaPreset(p,cr0,ci0,span){const[w,h]=dims(),n=640,c2=document.createElement('canvas');c2.width=c2.height=n;const x2=c2.getContext('2d'),id=x2.createImageData(n,n),d=id.data,hex=c=>[1,3,5].map(i=>parseInt(c.slice(i,i+2),16)),A=hex(p[1]),B=hex(p[2]),cr=cr0+Math.sin(state.variation*.1)*.02,ci=ci0+Math.cos(state.variation*.1)*.02;for(let y=0;y<n;y++)for(let x=0;x<n;x++){let zr=(x/n-.5)*span,zi=(y/n-.5)*span,it=0;for(;it<120&&zr*zr+zi*zi<4;it++){const t=zr*zr-zi*zi+cr;zi=2*zr*zi+ci;zr=t}const k=it/120,m=(1-k)*.5,o=(y*n+x)*4;d[o]=A[0]*k+B[0]*m;d[o+1]=A[1]*k+B[1]*m;d[o+2]=A[2]*k+B[2]*m;d[o+3]=it===120?40:220}x2.putImageData(id,0,0);ctx.save();ctx.globalAlpha=.75;const s=Math.max(w,h);ctx.drawImage(c2,(w-s)/2,(h-s)/2,s,s);ctx.restore()}
 function dendrite(p){juliaPreset(p,0,1,3)}
 function douady(p){juliaPreset(p,-.123,.745,3)}
 function siegel(p){juliaPreset(p,-.391,-.587,3)}
 function seahorse(p){juliaPreset(p,-.75,.11,3.2)}
 function starfield(p){const[w,h]=dims(),r=rand();ctx.save();for(let i=0;i<420;i++){const x=r()*w,y=r()*h,s=r()*r()*w*.006+1;ctx.fillStyle=i%7===0?p[1]:i%5===0?p[2]:p[3];ctx.globalAlpha=.3+r()*.7;ctx.fillRect(x,y,s,s)}ctx.restore()}
 return{acidblobs,oscilloscope,equalizer,circuitry,cybergrid,vortex,halftone,glitch,cassette,drummachine,flyers,memphis,lasergrid,neonwaves,strobestripes,synthwavesun,plasma,soundwaves,checkerwarp,holographic,acidsmileys,mandelbrot,julia,burningjulia,tricorn,nova,phoenixjulia,dendrite,douady,siegel,seahorse,starfield};
}
